name: test

on:
  workflow_dispatch:
    inputs:
      release_version:
        description: 'Release version'
        required: true

jobs:

  hotfix:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Update CHANGELOG.md
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git checkout main
          > CHANGELOG.md
          echo "# Версия ${{ github.run_number }}" | cat - CHANGELOG.md > temp && mv temp CHANGELOG.md
          echo "" >> CHANGELOG.md
          echo "Список коммитов от предыдущего релизного (или фиксрелизного) тега:" >> CHANGELOG.md
          echo "${{ steps.get-commits.outputs.log_changes }}" >> CHANGELOG.md
          git add CHANGELOG.md
          git commit -m "Update CHANGELOG for release ${{ github.run_number }}"
          git pull origin main
          git push https://${{ secrets.PA_TOKEN }}@github.com/${{ github.repository }}.git HEAD:main
        env:
          GITHUB_TOKEN: ${{ secrets.PA_TOKEN }} 
